# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/guivi/Downloads/P3_baseline/nn_rd_mems.xpr/nn_rd_mems/nn_rd_mems.srcs/sources_1/ip/images_mem/images_mem.xci
# IP: The module: 'images_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/guivi/Downloads/P3_baseline/nn_rd_mems.xpr/nn_rd_mems/nn_rd_mems.gen/sources_1/ip/images_mem/images_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'images_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/guivi/Downloads/P3_baseline/nn_rd_mems.xpr/nn_rd_mems/nn_rd_mems.srcs/sources_1/ip/images_mem/images_mem.xci
# IP: The module: 'images_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/guivi/Downloads/P3_baseline/nn_rd_mems.xpr/nn_rd_mems/nn_rd_mems.gen/sources_1/ip/images_mem/images_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'images_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
