# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/guivi/OneDrive - Universidade de Lisboa/Documentos/Faculdade/PSD/baseline.xpr/nn_rd_mems.xpr/nn_rd_mems/nn_rd_mems.srcs/sources_1/ip/weights1/weights1.xci
# IP: The module: 'weights1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/guivi/OneDrive - Universidade de Lisboa/Documentos/Faculdade/PSD/baseline.xpr/nn_rd_mems.xpr/nn_rd_mems/nn_rd_mems.gen/sources_1/ip/weights1/weights1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weights1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/guivi/OneDrive - Universidade de Lisboa/Documentos/Faculdade/PSD/baseline.xpr/nn_rd_mems.xpr/nn_rd_mems/nn_rd_mems.srcs/sources_1/ip/weights1/weights1.xci
# IP: The module: 'weights1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/guivi/OneDrive - Universidade de Lisboa/Documentos/Faculdade/PSD/baseline.xpr/nn_rd_mems.xpr/nn_rd_mems/nn_rd_mems.gen/sources_1/ip/weights1/weights1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weights1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
